config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get '/oauth/connect', as: :login
  get '/oauth/callback', to: 'oauth#callback'
  
  get '/logout', to: 'oauth#logout'
  get '/user', to: 'users#show'

end

app/models/hapi_tag_feed.rb
class HapiTagFeed < OpenStruct
  
  def self.service 
    @service ||= TwitterService.new
  end
  
  def self.find(token)
    tag = ["sunrise", "sunset", "cats", "kittens", "foodporn", "beautiful", "happy", "earthporn", "love"].sample
    HapiTagFeed.new(service.hapi_tag_feed(tag, token)).data.map! { |post| Post.new(post) }
  end

end

app/models/post.rb
class Post < OpenStruct

  def poster_pic
    self.user[:profile_picture]
  end

  def poster_name
    self.user[:username]
  end

  def image
    self.images[:standard_resolution][:url]
  end
  
  def post_caption
    if self.caption 
      self.caption[:text] 
    else
      ""
    end
  end

  def like_count
    self.likes[:count]
  end

end

app/models/user.rb
class User < OpenStruct

  def self.service
    @service ||= TwitterService.new
  end

  def self.find(id, token)
    User.new(service.user(id, token))
  end
  
  def username
    self.data[:username]
  end
  
  def full_name
    self.data[:full_name]
  end

  def profile_picture
    self.data[:profile_picture]
  end

  def bio
    self.data[:bio]
  end

  def posts
    self.data[:counts][:media]
  end

  def followers
    self.data[:counts][:follows]
  end

  def following
    self.data[:counts][:followed_by]
  end

end

app/models/user_feed.rb
class UserFeed < OpenStruct
  
  def self.service 
    @service ||= TwitterService.new
  end
  
  def self.find(id, token)
    UserFeed.new(service.user_feed(id, token)).data.map! { |post| Post.new(post) }
  end

end

app/models/user_media.rb
class UserMedia < OpenStruct

  def self.service
    @service ||= TwitterService.new
  end

  def self.find(id, token)
    UserMedia.new(service.user_media(id, token)).data.map! { |post| Post.new(post) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => ENV["callback_url"])
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => ENV["callback_url"])
    session[:access_token] = response.access_token
    session[:user] = response.user
    redirect_to user_path
  end

  def logout
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    token = session[:access_token]
    @user = User.find('self', token)
    @posts = UserFeed.find('self', token)
    @user_media = UserMedia.find('self', token)
    @hapi_tag_feed = HapiTagFeed.find(token)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hapipics</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lobster' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_comment.html.erb
<div class = "comment hidden">
  <p class = "comment-from">
    <%= "#{comment[:from][:username]} - " %>
  </p>
  <p class = "comment-text">
    <%= comment[:text] %>
  </p>
</div>

app/views/users/_post.html.erb
<div class="post">
  <div class="post-header">
    <div class="mini-profile-pic pull-left">
      <%= image_tag post.poster_pic %>
    </div>
    <h4 class = "pull-left"><%= post.poster_name %></h4> 
  </div>
  <div class = "pic-wrapper">
    <%= image_tag post.image %>
  </div>
  <div class = "caption">
    <%= post.post_caption %>
  </div>
  <div class = "likes">
    <%= "#{post.like_count} likes" %>
  </div>
  <div class="comments">
    <h5 class="btn">
      <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
      Comments
      <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
    </h5>
    <% @comments = post[:comments][:data] %>
    <div class = "comments-contents">
      <%= render partial: "comment", collection: @comments %> 
    </div>
  </div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <h1 class = "logito pull-left hidden shrunk-nav">HapiPics</h1>
  <h3 class = "username pull-right hidden shrunk-nav"><%= @user.username %></h3>

  <div class="full-nav col-md-2 full-nav">
    <h1 class = "logo">HapiPics</h1>
    <br>
    <%= link_to 'Log out', logout_path %><br>
  </div>

  <div class="profile-pic col-md-2 pull-right full-nav">
    <%= image_tag @user.profile_picture %><br>
  </div>
  
  <div class = "profile-counts col-md-2 pull-right full-nav">
    <table class="counts pull-right">
      <h4 class = "text-right"><%= @user.full_name %></h4>
      <tbody class = "pull-right">
	<tr>
	  <td><h5>Posts</h5></td>
	  <td><%= @user.posts %></td>
	</tr>
	<tr>
	  <td><h5>Followers</h5></td>
	  <td><%= @user.followers %></td>
	</tr>
	<tr>
	  <td><h5>Following</h5></td>
	  <td><%= @user.following %></td>
	</tr>
      </tbody>
    </table>
  </div>
  
  <div class="profile-info col-md-6 pull-right full-nav">
    <h3><%= @user.username %></h3><br>
    <div class = "bio"> 
      <p><%= @user.bio %></p><br>
    </div>
  </div>
</nav>

 
<div class="container">
  <div class="feed user-current-feed col-md-8 col-md-offset-2">
    <%= render partial: "post", collection: @posts  %>
  </div>
  <div class="feed user-media hidden col-md-8 col-md-offset-2">
    <%= render partial: "post", collection: @user_media  %>
  </div>
  <div class="feed hapi-feed hidden col-md-8 col-md-offset-2">
    <%= render partial: "post", collection: @hapi_tag_feed  %>
  </div>
  <h3 class = "btn feed-selector current active">Current Feed</h3>
  <h3 class = "btn feed-selector media">My Media</h3>
  <h3 class = "btn feed-selector hapi-tag-feed">Hapi Tag</h3>
</div>

app/views/welcome/index.html.erb
<div id="bg_container">
  <div class="splash text-center">
    <h1>HapiPics</h1>
    <%= link_to 'Login with Instagram', login_path, class: "btn btn-default hidden" %>
    <p>We put the 'api' in hapi</p>
  </div>
</div>

<%= javascript_include_tag "jquery.tubular.1.0.js" %>
<%= javascript_include_tag "splash.js" %>